CREATE TABLE users (
	id_user INT AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL,
	description VARCHAR(50) NOT NULL,
	image VARCHAR(100) NOT NULL,
	password VARCHAR(50) NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY(id_user)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;